Ödev: Bir E-Ticaret Şirketi İçin Veri Analizi ve Raporlama
Ödev Açıklaması:
Bir e-ticaret şirketinde çalıştığınızı hayal edin. Şirket, müşterilerin alışveriş alışkanlıklarını anlamak, en çok satan ürünleri belirlemek ve kârlılığı artırmak için veri analizi yapmanızı istiyor. Size verilen satış verilerini NumPy kullanarak analiz etmeniz gerekiyor.

1. Veri Seti (Üretilmesi Gereken Rastgele Veriler)
Her öğrenci rastgele üretilmiş verilere dayalı analiz yapmalıdır. Aşağıdaki verileri NumPy kullanarak oluşturun:

1000 müşterinin harcama tutarları (50 TL ile 5000 TL arasında rastgele)
1000 müşterinin satın aldığı ürün sayıları (1 ile 10 arasında rastgele)
1000 müşterinin indirimden yararlanıp yararlanmadığı (0: Hayır, 1: Evet - %30 indirim aldı)
Ürün fiyatları (10 TL ile 1000 TL arasında rastgele)
Kategori bazlı satış adetleri (5 kategori için rastgele satış sayıları)


2. İstenilen Analizler
Aşağıdaki analizleri gerçekleştirin:

A. Temel İstatistikler
Ortalama müşteri harcaması nedir? (mean)
En yüksek ve en düşük harcama miktarları nedir? (max, min)
B. Satış Analizi
İndirim kullanan müşterilerin ortalama harcaması ile indirim kullanmayanların ortalama harcaması arasındaki farkı bulun.
Toplam satış gelirini hesaplayın.
En çok satılan ürünleri ve kategorileri belirleyin.
Satın alınan ürün sayısı ile harcama arasında korelasyon var mı? (np.corrcoef() kullanarak)
C. Sezonluk Karşılaştırma (Geçen Yılla Kıyaslama)
Geçen yılın verilerini rastgele oluşturarak bu yıl ile karşılaştırın. Satışlarda ortalama % kaç artış veya azalma olmuş?
Geçen yıl en çok satılan ürün ile bu yıl en çok satılan ürünü karşılaştırın.
D. Stratejik Kararlar
Elde edilen verilere dayanarak e-ticaret şirketine 3 öneri sunun. (Örneğin, indirimlerin satışlara etkisini değerlendirerek)

---



In [ ]:
import numpy as np

In [ ]:
product_counts = np.random.randint(1, 11, 1000)
print(product_counts)

[ 8  9 10  8  1  2  1  1  7  6  8  4  2  1  7  8  4  1  8  5  1  3  4  1
  6  2  3  6  5  8  9  2  7  2  8  1  3  1  2  2  4  6  8  5  7  8  4  7
  6  2  3  1  9  4  7  4  3  8  8 10 10  6  9  5  8  1 10  2  9  4  1  1
  3  9  1  6  8  8  5  6  8  8  6  9  5  3 10  1  7  2  5  2  8  4  9 10
  7 10 10 10  1  6  9  8  9  6  8  1  1  4  9  2  3  8  2  1  4  3  5  1
  4  6 10  8  1  2  9  4  4  7  9  7  3  9  2  4  5  5  2  2  6  4  3  3
  7 10  8  8  4  3  8  9  6  3  6  7 10  2  9  8  9  3  4  6  2  3  6  4
  1  3  9  7  5  5  4  1  6  5  7  3  1  3  9  4  6  1  7  8  2 10  7  4
  3  6  6  4  8  1 10  6  8  6  2  9  6  8  8  8  9  6  5  1  5  6  1  5
  9  7  9 10  8  6  1  8  9  7  1  1  2  6  4  7 10  3  5  5  2  4  3  1
  6  3  8  9  7  8  6  3  4  1  3  8  3  7  6 10  3  5  7  2  6  2  8 10
  1  8  7  8  6  7  7  3  8  3  6  7  7  8  6  9  2  4  5  1  4  1  7 10
  1  8  1 10  9  3  6  9  3  2  7  9  7  1 10  9 10  8  2  8  6  2  7  6
  3 10  5  1  5  8 10  8  1  5  3  5  9  8  5 10  4

In [ ]:
discount_usage = np.random.randint(0, 2, 1000)
print(discount_usage)

[1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1
 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1
 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0
 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0
 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 0
 1 0 0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1
 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 0 1
 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0
 1 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0
 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1
 1 1 1 1 0 1 0 0 0 0 0 1 

In [ ]:
product_prices = np.random.randint(10, 1001, 5)
print(product_prices)

[ 69 804 461 930 251]


In [ ]:
categories_salescount = np.zeros((5,1000), dtype=int)
##print(categories_salescount)

for i in range(1000):
    sales_counts = np.random.multinomial(product_counts[i], [0.2, 0.2, 0.2, 0.2, 0.2])
    categories_salescount[:, i] = sales_counts

print(categories_salescount)


[[0 2 0 ... 3 4 1]
 [5 3 4 ... 1 2 2]
 [0 1 4 ... 1 1 0]
 [2 3 2 ... 3 0 2]
 [1 0 0 ... 1 1 1]]


In [ ]:
np.sum(categories_salescount.T * product_prices, axis=1)

array([6131, 5801, 6920, 3632,  251, 1734,  251,   69, 4375, 2815, 3331,
       2663, 1265,   69, 1890, 2645, 1746,  930, 2932, 2641,   69, 2195,
       1795,  804, 3571,  999, 1250, 2402, 2354, 3611, 3855,  712, 2968,
       1055, 3905,   69, 1516,  461, 1265,  999, 2054, 1562, 4556, 2641,
       3794, 4451, 1585, 4382, 3998,  999, 1306,  251, 4072, 1011, 2709,
       2054,  571, 4836, 4423, 4169, 4904, 2325, 3057, 1262, 4374,  804,
       5240,  712, 5612, 1711,  930,  251, 1432, 4359,  804, 2402, 4416,
       3457, 3593, 2640, 4444, 3821, 4642, 6501, 3376, 1852, 3567,  251,
       3283,  320, 3243, 1391, 4241, 1928, 5458, 4477, 4333, 2965, 3854,
       4197,  930, 1849, 4142, 3975, 3624, 3445, 2561,  930,  804, 2446,
       4877,  530, 1642, 2904,  530,  461, 2264, 1929, 2984,  251, 1032,
       1639, 5030, 2904,  930,  999, 2420, 1711, 1893, 3514, 6592, 3227,
       1803, 2791, 1734, 2446, 2459, 3250,  712, 1734, 3655, 1977, 1852,
        599, 2527, 3301, 3422, 2512, 1767, 1334, 46

In [ ]:
spending_totals=np.array([])
for i in range(1000):
  if discount_usage[i] == 0:
    spending_totals=np.sum(categories_salescount.T * product_prices, axis=1)
  else:
    spending_totals=np.sum(categories_salescount.T * product_prices, axis=1)*0.7

print(spending_totals)

[4291.7 4060.7 4844.  2542.4  175.7 1213.8  175.7   48.3 3062.5 1970.5
 2331.7 1864.1  885.5   48.3 1323.  1851.5 1222.2  651.  2052.4 1848.7
   48.3 1536.5 1256.5  562.8 2499.7  699.3  875.  1681.4 1647.8 2527.7
 2698.5  498.4 2077.6  738.5 2733.5   48.3 1061.2  322.7  885.5  699.3
 1437.8 1093.4 3189.2 1848.7 2655.8 3115.7 1109.5 3067.4 2798.6  699.3
  914.2  175.7 2850.4  707.7 1896.3 1437.8  399.7 3385.2 3096.1 2918.3
 3432.8 1627.5 2139.9  883.4 3061.8  562.8 3668.   498.4 3928.4 1197.7
  651.   175.7 1002.4 3051.3  562.8 1681.4 3091.2 2419.9 2515.1 1848.
 3110.8 2674.7 3249.4 4550.7 2363.2 1296.4 2496.9  175.7 2298.1  224.
 2270.1  973.7 2968.7 1349.6 3820.6 3133.9 3033.1 2075.5 2697.8 2937.9
  651.  1294.3 2899.4 2782.5 2536.8 2411.5 1792.7  651.   562.8 1712.2
 3413.9  371.  1149.4 2032.8  371.   322.7 1584.8 1350.3 2088.8  175.7
  722.4 1147.3 3521.  2032.8  651.   699.3 1694.  1197.7 1325.1 2459.8
 4614.4 2258.9 1262.1 1953.7 1213.8 1712.2 1721.3 2275.   498.4 1213.8
 2558.5 

In [ ]:
##Ortalama müşteri harcaması nedir? (mean)
avg_spending = np.mean(spending_totals)
print(avg_spending)

2019.4902


In [ ]:
##En yüksek ve en düşük harcama miktarları nedir? (max, min)
max_spending = np.max(spending_totals)
min_spending = np.min(spending_totals)
print(max_spending)
print(min_spending)

5681.9
48.3


In [ ]:
##Kaç müşteri indirim kullanmıştır? (sum)
discount_usage_count = np.sum(discount_usage ==1)
print(discount_usage_count)

516


In [ ]:
##İndirim kullanan müşterilerin ortalama harcaması ile indirim kullanmayanların ortalama harcaması arasındaki farkı bulun.
avg_spending = np.mean(spending_totals[discount_usage == 1])
avg_spending_without_discount = np.mean(spending_totals[discount_usage == 0])
print(avg_spending)
print(avg_spending_without_discount)
difference = avg_spending - avg_spending_without_discount
print(difference)

1966.2335271317827
2076.2679752066115
-110.03444807482879


In [ ]:
##Toplam satış gelirini hesaplayın.
total_sales = np.sum(spending_totals)
print(total_sales)

2019490.2


In [ ]:
##En çok satılan ürünleri ve kategorileri belirleyin.
most_sold_product = np.argmax(np.sum(categories_salescount, axis=1))
print(most_sold_product)

print(max(np.sum(categories_salescount, axis=1)))

2
1207


In [ ]:
##Satın alınan ürün sayısı ile harcama arasında korelasyon var mı? (np.corrcoef() kullanarak)
correlation = np.corrcoef(product_counts, spending_totals)
print(correlation)



[[1.         0.89112855]
 [0.89112855 1.        ]]


In [ ]:
last_year_product_counts = np.random.randint(1, 11, 1000)
print(product_counts)

[ 8  9 10  8  1  2  1  1  7  6  8  4  2  1  7  8  4  1  8  5  1  3  4  1
  6  2  3  6  5  8  9  2  7  2  8  1  3  1  2  2  4  6  8  5  7  8  4  7
  6  2  3  1  9  4  7  4  3  8  8 10 10  6  9  5  8  1 10  2  9  4  1  1
  3  9  1  6  8  8  5  6  8  8  6  9  5  3 10  1  7  2  5  2  8  4  9 10
  7 10 10 10  1  6  9  8  9  6  8  1  1  4  9  2  3  8  2  1  4  3  5  1
  4  6 10  8  1  2  9  4  4  7  9  7  3  9  2  4  5  5  2  2  6  4  3  3
  7 10  8  8  4  3  8  9  6  3  6  7 10  2  9  8  9  3  4  6  2  3  6  4
  1  3  9  7  5  5  4  1  6  5  7  3  1  3  9  4  6  1  7  8  2 10  7  4
  3  6  6  4  8  1 10  6  8  6  2  9  6  8  8  8  9  6  5  1  5  6  1  5
  9  7  9 10  8  6  1  8  9  7  1  1  2  6  4  7 10  3  5  5  2  4  3  1
  6  3  8  9  7  8  6  3  4  1  3  8  3  7  6 10  3  5  7  2  6  2  8 10
  1  8  7  8  6  7  7  3  8  3  6  7  7  8  6  9  2  4  5  1  4  1  7 10
  1  8  1 10  9  3  6  9  3  2  7  9  7  1 10  9 10  8  2  8  6  2  7  6
  3 10  5  1  5  8 10  8  1  5  3  5  9  8  5 10  4

In [ ]:
last_year_discount_usage = np.random.randint(0, 2, 1000)
print(discount_usage)

[1 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1
 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1
 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0
 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0
 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 0
 1 0 0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1
 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 0 1
 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0
 1 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0
 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1
 1 1 1 1 0 1 0 0 0 0 0 1 

In [ ]:
last_year_product_prices = np.random.randint(10, 1001, 5)
print(product_prices)

[ 69 804 461 930 251]


In [ ]:
last_year_categories_salescount = np.zeros((5,1000), dtype=int)
##print(categories_salescount)

for i in range(1000):
    sales_counts = np.random.multinomial(last_year_product_counts[i], [0.2, 0.2, 0.2, 0.2, 0.2])
    last_year_categories_salescount[:, i] = sales_counts

print(last_year_categories_salescount)

[[1 2 3 ... 1 0 1]
 [3 1 2 ... 0 0 2]
 [0 0 1 ... 4 1 2]
 [0 1 3 ... 1 0 2]
 [1 0 0 ... 1 1 3]]


In [ ]:
last_year_spending_totals=np.array([])
for i in range(1000):
  if discount_usage[i] == 0:
    last_year_spending_totals=np.sum(last_year_categories_salescount.T * last_year_product_prices, axis=1)
  else:
    last_year_spending_totals=np.sum(last_year_categories_salescount.T * last_year_product_prices, axis=1)*0.7

print(last_year_spending_totals)

[2420.6 2510.2 5436.9 4004.  2988.3 1600.2 3936.8 4814.6 2317.  4711.
  490.7 3375.4 4650.8 4475.8 3443.3 4424.7 4363.1 3888.5 4204.9 3768.8
 5485.2 1665.3 2807.  3101.  1629.6 5346.6 5111.4 5466.3 5178.6  490.7
  683.9 1794.1  448.7 2571.8 5014.1 4663.4 4059.3 2601.2 4440.1 3781.4
 3743.6  448.7 3182.2 1430.1  490.7 5079.2 1213.1 1623.3 3898.3 5079.2
 1407.   948.5 3072.3 4211.2 4820.9 5082.7  651.7 3592.4 3969.7 5121.2
  529.2 3301.2 4389.  2313.5 3200.4 1752.1 3817.8  490.7 2833.6 4091.5
 4240.6 3720.5 3550.4 4527.6 1426.6  977.9  448.7  651.7 1100.4 1100.4
 5114.9 3720.5  683.9 2646.7 1510.6 1367.8 3866.1  490.7 3619.7 1407.
  948.5 2926.7 1864.8 1132.6 4130.7 5908.  2539.6 2346.4 4946.2 1858.5
  529.2 2979.2  939.4 2420.6  683.9 4220.3 2114.  2484.3 5144.3 3184.3
 2581.6 3549.7 4291.7 2604.7 2998.1 2336.6 5056.1 3521.  4692.1 4484.9
 5079.2 3488.8 5166.   939.4 2914.1 5047.   264.6 1142.4 1826.3 5111.4
 3785.6  448.7 4579.4 1365.   916.3 3536.4 3818.5  490.7 2114.  2926.7
 2284.8 

In [ ]:
##Satışlarda ortalama % kaç artış veya azalma olmuş?
sales_growth = (np.mean(spending_totals) - np.mean(last_year_spending_totals)) / np.mean(last_year_spending_totals) * 100
print(sales_growth)

-28.945694297525648


In [ ]:
##Geçen yıl en çok satılan ürün ile bu yıl en çok satılan ürünü karşılaştırın.
last_year_most_sold_product = np.argmax(np.sum(last_year_categories_salescount, axis=1))
print(last_year_most_sold_product)

print(np.array([most_sold_product,last_year_most_sold_product]))

1
[2 1]


##Elde edilen verilere dayanarak e-ticaret şirketine 3 öneri sunun. (Örneğin, indirimlerin satışlara etkisini değerlendirerek)

1- Geçen yıl en çok satılan kategorinin bu kod parçası ile 0. kategori olduğunu bulduk, bu sene ise 4 olduğunu gözlemledik. Müşteri davranışlarının incelenmesini öneririz.

2- En çok ürün alan müşterilerin en çok harcamayı yapan müşteriler olmadığı tespit edilmiştir. Satın alınan ürün sayısı ile harcanan tutar arasında güçlü bir ilişki saptanmamıştır.

3- İndirim kullanan müşterinin ortalama harcamasının yüksek veya düşük olmasına göre indirim kampanyalarının kar marjı üzerindeki etkisi gözden geçirilmelidir. İndirim kullanan müşterilerin ortalaması indirim kullanmayan müşterilerden daha az olduğu için müşteri segmentasyonuna göre kampanyalar düzenlenmelidir.